spring:
  main.web-application-type: NONE
  # datasource:
  #   url: "jdbc:postgresql://localhost:5432/catalog?autoReconnect=true"
  #   username: postgres
  #   password: postgres
  #   driverClassName: org.postgresql.Driver
  #   validation-query: select 1;
  #   maxActive: 100
  # datasource:
  #   url: jdbc:h2:mem:mydb
  #   username: sa
  #   password: password
  #   driverClassName: org.h2.Driver
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false