spring:
  main.web-application-type: NONE
  datasource:
    url: "jdbc:postgresql://localhost:5432/catalog?autoReconnect=true"
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    validation-query: select 1;
    maxActive: 100
  jpa:
    show-sql: true
    generate-ddl: false